---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: migrated-gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: ASR Runtime
    opendatahub.io/template-name: asr-runtime
    openshift.io/display-name: whisper-kserve-vllm
  name: whisper-kserve-vllm
  namespace: whisper
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8888'
  containers:
    - image: 'quay.io/rlundber/whisper-vllm-kserve:s3-preprocessing'
      imagePullPolicy: Always
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
      envFrom:
        - secretRef:
            name: audio
  multiModel: false
  protocolVersions:
    - v1
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
      version: '1'
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
