kind: ConfigMap
apiVersion: v1
metadata:
  name: model-configs
  namespace: whisper
immutable: false
data:
  config.pbtxt: |-
    name: "whisper"
    backend: "vllm"
    max_batch_size: 0

    input [
      {
        name: "TEXT_PREFIX"
        data_type: TYPE_STRING
        dims: [1]
      },
      {
        name: "WAV"
        data_type: TYPE_FP32
        dims: [-1]
      }
    ]

    output [
      {
        name: "TRANSCRIPTS"
        data_type: TYPE_STRING
        dims: [1]
      }
    ]

    instance_group [
      {
        count: 1
        kind: KIND_MODEL
      }
    ]
  model.json: |-
    {
        "model": "/mnt/models/model_repository/whisper/whisper",
        "disable_log_requests": "true",
        "gpu_memory_utilization": 0.95
    }
