---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: whisper-triton-vllm
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8002'
  containers:
    - args:
        - tritonserver
        - '--model-store=/mnt/models/model_repository'
        - '--log-verbose=1'
      env:
        - name: VLLM_NO_USAGE_STATS
          value: '1'
        - name: DO_NOT_TRACK
          value: '1'
      image: 'nvcr.io/nvidia/tritonserver:25.02-vllm-python-py3'
      name: kserve-container
      volumeMounts:
        - mountPath: /mnt/models/model_repository/whisper/1/model.json
          name: model-configs
          subPath: model.json
        - mountPath: /mnt/models/model_repository/whisper/config.pbtxt
          name: model-configs
          subPath: config.pbtxt
      readinessProbe:
        tcpSocket:
          port: 8000
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
  protocolVersions:
    - v2
    - grpc-v2
  supportedModelFormats:
    - name: triton
      version: '2'
  volumes:
    - configMap:
        items:
          - key: model.json
            path: model.json
          - key: config.pbtxt
            path: config.pbtxt
        name: model-configs
      name: model-configs
